### PR TITLE
Add screenshot to readme

### PR DESCRIPTION
**Pull request by StefKors**
A screenshot makes it easier to see what the package looks like 😄

### CODE REVIEW

**Comment by grimmerk** [comment]
@StefKors  Thank you so much. It's very good to see the screenshot.

I check several extensions listed in https://marketplace.visualstudio.com/VSCode and most of them put screenshots in the extension repo, such as https://raw.githubusercontent.com/microsoft/vscode-remote-repositories-github/main/docs/remote-repositories.gif. I think it is a good place to host. Do you mind that copying the screenshot to this repo? If so, I can copy it, and either you or I revise the link and merge this PR.

**Comment by grimmerk** [comment]
@StefKors Did you see the above message?

**Comment by StefKors** [comment]
Hey! Yes, feel free to put it wherever it's needed 👍

**Review by grimmerk — COMMENTED** [review]
I have published a new version. Thank you.

**Pull request merged**
